In [1]:
import pycqed as pq
import numpy as np
from pycqed.measurement import measurement_control
from pycqed.measurement.sweep_functions import None_Sweep
import pycqed.measurement.detector_functions as det
from qcodes import station
station = station.Station()


Data directory set to: None


## Creating an instance of the measurement control

Measurements are controlled through the `MeasurementControl` usually instantiated as `MC`

In [2]:
MC = measurement_control.MeasurementControl('MC',live_plot_enabled=True, verbose=True)
MC.station = station
station.add_component(MC)

'MC'

In [3]:
from pycqed.instrument_drivers.virtual_instruments import instrument_monitor as im 
IM = im.InstrumentMonitor('IM', station)
station.add_component(IM)
# Link the instrument monitor to the MC so that it gets updated in the loop
MC.instrument_monitor('IM')

## Create instruments used in the experiment 
Let's start by creating a dummy instrument called MockParabola. 


In [4]:
from pycqed.instrument_drivers.physical_instruments.dummy_instruments import DummyParHolder
dummy_instrument = DummyParHolder('dummy_instrument')
station.add_component(dummy_instrument)

'dummy_instrument'

## A 1D hard measurement 
A hard measurement is a measurement where the data acquisition loop happens in the **hard**ware.

In [5]:
MC.soft_avg(15)
MC.persist_mode(True)
MC.set_sweep_function(None_Sweep(sweep_control='hard'))
MC.set_sweep_points(np.linspace(0, 10, 30))
MC.set_detector_function(det.Dummy_Detector_Hard(noise=0.5, delay=.02))
dat = MC.run('dummy_hard')
data_set = dat['dset']

Starting measurement: dummy_hard
Sweep function: None_Sweep
Detector function: Dummy_Detector
 100% completed 	elapsed time: 1.0s 	time left: 0.0s


By setting persist_mode = True we can see a copy of the last measurements

In [6]:

MC.set_sweep_function(None_Sweep(sweep_control='hard'))
MC.set_sweep_points(np.linspace(0, 10, 30))
MC.set_detector_function(det.Dummy_Detector_Hard(noise=0.5, delay=.02))
dat2 = MC.run('dummy_hard persistent')
data_set2 = dat2['dset']
print(data_set2)

Starting measurement: dummy_hard persistent
Sweep function: None_Sweep
Detector function: Dummy_Detector
 100% completed 	elapsed time: 1.4s 	time left: 0.0s
[[  0.00000000e+00  -8.41805618e-03   9.52221751e-01]
 [  3.44827592e-01   5.64679876e-02   9.63823080e-01]
 [  6.89655185e-01   2.71647215e-01   9.90496159e-01]
 [  1.03448272e+00   3.58638942e-01   9.83597755e-01]
 [  1.37931037e+00   4.11285490e-01   8.58026862e-01]
 [  1.72413790e+00   4.77858633e-01   7.64453173e-01]
 [  2.06896544e+00   6.31779075e-01   7.80045271e-01]
 [  2.41379309e+00   6.28673434e-01   7.12422073e-01]
 [  2.75862074e+00   8.28549922e-01   6.89963996e-01]
 [  3.10344839e+00   8.08600903e-01   5.54980338e-01]
 [  3.44827580e+00   8.77372682e-01   4.91556764e-01]
 [  3.79310346e+00   9.23762381e-01   4.19212967e-01]
 [  4.13793087e+00   9.73725736e-01   2.85644293e-01]
 [  4.48275852e+00   9.79517102e-01   7.03447387e-02]
 [  4.82758617e+00   1.05004179e+00   5.40984496e-02]
 [  5.17241383e+00   1.08093548e

# A simple 1D soft measurement 
A soft measurement is a a measurement where the data acquisition loop occurs in the **soft**ware

In [8]:
dummy_instrument.x(145/134545)
IM.update()

In [9]:
dummy_instrument.delay(.01)
MC.soft_avg(15)
MC.set_sweep_function(dummy_instrument.x)
MC.set_sweep_points(np.linspace(-1,1,30))
dummy_instrument.noise(1)

MC.set_detector_function(dummy_instrument.parabola)
dat = MC.run('1D test')
data_set = dat['dset']

# the second plot will also show the first line
MC.set_sweep_function(dummy_instrument.x)
MC.set_sweep_points(np.linspace(-1,1,30))

dat2= MC.run('1D test-persist')
data_set2 = dat2['dset']

Starting measurement: 1D test
Sweep function: x
Detector function: parabola
 100% completed 	elapsed time: 6.6s 	time left: 0.0s
Starting measurement: 1D test-persist
Sweep function: x
Detector function: parabola
 100% completed 	elapsed time: 7.5s 	time left: 0.0s


You can play around a bit with the options in the MC: 

In [10]:
MC.persist_mode(True) # Turns on and off persistent plotting
MC.verbose(True)
MC.plotting_interval(.2)
MC.live_plot_enabled(True)

# A simple 2D measurement

In [10]:
dummy_instrument.delay(.0001)
MC.soft_avg(4)

sweep_pts = np.linspace(-2, 2, 30)
sweep_pts_2D = np.linspace(-2, 2, 5)

MC.set_sweep_function(dummy_instrument.x)
MC.set_sweep_function_2D(dummy_instrument.y)
MC.set_sweep_points(sweep_pts)
MC.set_sweep_points_2D(sweep_pts_2D)
MC.set_detector_function(dummy_instrument.parabola)
dat=MC.run('test', mode='2D')
data_set = dat['dset']


Starting measurement: test
Sweep function 0: x
Sweep function 1: Sweep_function
Detector function: parabola
 100% completed 	elapsed time: 5.2s 	time left: 0.0ss


# 2D combinatioin of a hard inner and soft outer loop
The hard inner loop returns 30 values 

In [9]:
MC.soft_avg(1)
sweep_pts = np.linspace(0, 10, 30)
sweep_pts_2D = np.linspace(0, 10, 30)
MC.set_sweep_function(None_Sweep(sweep_control='hard'))
MC.set_sweep_function_2D(None_Sweep(sweep_control='soft'))
MC.set_sweep_points(sweep_pts)
MC.set_sweep_points_2D(sweep_pts_2D)
MC.set_detector_function(det.Dummy_Detector_Hard(delay=.05, noise=.1))
dat = MC.run('2D_hard', mode='2D')
data_set = dat['dset']

Starting measurement: 2D_hard
Sweep function 0: None_Sweep
Sweep function 1: None_Sweep
Detector function: Dummy_Detector
 100% completed 	elapsed time: 14.0s 	time left: 0.0s


## A Hard measurement that uses soft averaging

The number of soft_averages determines how many times the experiment will be performed. 
Only the averaged data is plotted and saved. 
The number of soft-averages can be set as a parameter of the Measurement Control. 

Will first implement it for 1D hard sweeps (easier) and then follow for combinations of hard and soft sweeps. 

In [10]:
MC.soft_avg(4)
MC.set_sweep_function(None_Sweep(sweep_control='hard'))
MC.set_sweep_points(np.linspace(0, 10, 30))
MC.set_detector_function(det.Dummy_Detector_Hard(noise=1.5, delay=.02))

dat = MC.run('dummy_hard')
data_set = dat['dset']

Starting measurement: dummy_hard
Sweep function: None_Sweep
Detector function: Dummy_Detector
 100% completed 	elapsed time: 1.1s 	time left: 0.0s


# 2D soft averaging

In [11]:
MC.soft_avg(10)
sweep_pts = np.linspace(0, 10, 30)
sweep_pts_2D = np.linspace(0, 10, 5)
MC.set_sweep_function(None_Sweep(sweep_control='hard'))
MC.set_sweep_function_2D(None_Sweep(sweep_control='soft'))
MC.set_sweep_points(sweep_pts)
MC.set_sweep_points_2D(sweep_pts_2D)
MC.set_detector_function(det.Dummy_Detector_Hard(noise=1.5, delay=.001))

dat = MC.run('dummy_hard_2D', mode='2D')
data_set = dat['dset']

Starting measurement: dummy_hard_2D
Sweep function 0: None_Sweep
Sweep function 1: None_Sweep
Detector function: Dummy_Detector
 100% completed 	elapsed time: 16.7s 	time left: 0.0s



## Starting an adaptive measurement 
This example does a 2D optimization over the mock parabola

In [12]:
from pycqed.measurement.optimization import nelder_mead
MC.soft_avg(1)
dummy_instrument
MC.set_sweep_functions([dummy_instrument.x, dummy_instrument.y])
MC.set_adaptive_function_parameters({'adaptive_function':nelder_mead, 
                                    'x0':[-5,-5], 'initial_step': [2.5, 2.5]})
dummy_instrument.noise(.5)
MC.set_detector_function(dummy_instrument.parabola)
dat = MC.run('1D test', mode='adaptive')
data_set = dat['dset']

Starting measurement: 1D test
Sweep function 0: module
Sweep function 1: module
Detector function: parabola
Optimization completed in 1.564s
